# Use root/example as user/password credentials
version: '3.1'

services:

  backend:
    build: 
      dockerfile: Dockerfile
      context: ./backend
    environment:
      MYSQL_HOST: '${MYSQL_HOST}'
      MYSQL_PORT: '${MYSQL_PORT}'
      MYSQL_USERNAME: '${MYSQL_USERNAME}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      PORT: '${BACKEND_PORT}'
      SECRET: '${SECRET}'
    networks:
      - foodbear
    ports:
      - '127.0.0.1:${BACKEND_PORT}:${BACKEND_PORT}'
    depends_on:
      - db

  frontend:
    build: 
      dockerfile: Dockerfile
      context: .
    environment:
      PORT: '${FRONTEND_PORT}'
      BACKEND_PORT: '${BACKEND_PORT}'
      BACKEND_HOST: '${BACKEND_HOST}'
    networks:
      - foodbear
    ports:
      - '127.0.0.1:${FRONTEND_PORT}:${FRONTEND_PORT}'
    depends_on:
      - backend

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    networks: 
       - foodbear
    volumes:
       - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
       - 127.0.0.1:${MYSQL_PORT}:${MYSQL_PORT}

  phpmyadmin:
    image: phpmyadmin
    networks:
       - foodbear
    ports:
      - 127.0.0.1:8080:80
    depends_on:
      - db

networks:
  foodbear:
    driver: bridge

volumes:
  mysql:
    driver: local


