# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    networks: 
       - foodbear
    volumes:
       - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
       - 127.0.0.1:3306:3306

  phpmyadmin:
    image: phpmyadmin
    networks:
       - foodbear
    ports:
      - 127.0.0.1:8080:80

networks:
  foodbear:
    driver: bridge

volumes:
  mysql:
    driver: local


